[InputMethod]
Name=Hiraganify (Table)
Icon=fcitx_hiraganify
LangCode=ja
Addon=table
Configurable=True

[Table]
File=table/hiraganify.main.dict
OrderPolicy=No
AutoSelect=True
AutoSelectLength=1
NoMatchAutoSelectLength=0
Learning=False
ExactMatch=False
FirstCandidateAsPreedit=True
CommitInvalidSegment=True
